import React from 'react';
import { Feather } from '@expo/vector-icons';
import { Ionicons } from '@expo/vector-icons';

// Icons that exist in Feather - use Feather
// Icons that DON'T exist in Feather - fall back to Ionicons
const FEATHER_MAP = {
  'add': 'plus',
  'add-circle': 'plus-circle',
  'alert-circle': 'alert-circle',
  'apps-outline': 'grid',
  'arrow-back': 'arrow-left',
  'arrow-forward': 'arrow-right',
  'ban': 'x-octagon',
  'bar-chart': 'bar-chart-2',
  'business': 'home',
  'calendar': 'calendar',
  'calendar-outline': 'calendar',
  'call': 'phone',
  'camera': 'camera',
  'chatbubble': 'message-circle',
  'chatbubble-ellipses': 'message-circle',
  'chatbubble-outline': 'message-circle',
  'chatbubbles': 'message-square',
  'chatbubbles-outline': 'message-square',
  'checkmark': 'check',
  'checkmark-circle': 'check-circle',
  'checkmark-done': 'check-circle',
  'chevron-back': 'chevron-left',
  'chevron-down': 'chevron-down',
  'chevron-forward': 'chevron-right',
  'clipboard': 'file-text',
  'clipboard-outline': 'file-text',
  'close': 'x',
  'close-circle': 'x-circle',
  'create': 'edit-2',
  'create-outline': 'edit-2',
  'download': 'download',
  'flag-outline': 'flag',
  'flash': 'zap',
  'folder': 'folder',
  'gift': 'gift',
  'gift-outline': 'gift',
  'grid': 'grid',
  'heart': 'heart',
  'heart-outline': 'heart',
  'hourglass': 'clock',
  'info-circle': 'info',
  'information-circle': 'info',
  'language': 'globe',
  'location': 'map-pin',
  'lock-closed': 'lock',
  'lock-closed-outline': 'lock',
  'log-out-outline': 'log-out',
  'mail': 'mail',
  'mail-outline': 'mail',
  'map': 'map',
  'map-outline': 'map',
  'megaphone': 'volume-2',
  'megaphone-outline': 'volume-2',
  'mic': 'mic',
  'moon': 'moon',
  'navigate': 'navigation',
  'notifications': 'bell',
  'notifications-off-outline': 'bell-off',
  'pencil': 'edit-2',
  'people': 'users',
  'people-outline': 'users',
  'users': 'users',
  'person': 'user',
  'person-outline': 'user',
  'receipt-outline': 'file-text',
  'refresh': 'refresh-cw',
  'ribbon': 'award',
  'search': 'search',
  'search-outline': 'search',
  'send': 'send',
  'settings': 'settings',
  'share-outline': 'share-2',
  'share-social': 'share-2',
  'shield': 'shield',
  'shield-checkmark': 'shield',
  'sparkles': 'star',
  'star': 'star',
  'star-outline': 'star',
  'storefront': 'briefcase',
  'storefront-outline': 'briefcase',
  'time': 'clock',
  'trash': 'trash-2',
  'trash-outline': 'trash-2',
  'warning': 'alert-triangle',
  'warning-outline': 'alert-triangle',
  'water-outline': 'droplet',
  'water': 'droplet',
  'flash-outline': 'zap',
  'hammer-outline': 'tool',
  'hammer': 'tool',
  'construct': 'tool',
  'construct-outline': 'tool',
  'brush-outline': 'edit-3',
  'leaf-outline': 'feather',
  'text': 'type',
  'car-outline': 'truck',
  'cut-outline': 'scissors',
  'bicycle-outline': 'activity',
  'fitness-outline': 'heart',
  'restaurant-outline': 'coffee',
  'medical-outline': 'activity',
  'school-outline': 'book',
  'home-outline': 'home',
  'globe-outline': 'globe',
  'shield-checkmark-outline': 'shield',
  'briefcase-outline': 'briefcase',
  'code-outline': 'code',
  'film-outline': 'film',
  'musical-notes-outline': 'music',
  'camera-outline': 'camera',
  'book-outline': 'book',
  'paw-outline': 'heart',
  'airplane-outline': 'navigation',
  'arrow-left': 'arrow-left',
  'check': 'check',
  'check-circle': 'check-circle',
  'chevron-up': 'chevron-up',
  'eye-off-outline': 'eye-off',
  'eye-outline': 'eye',
  'file-text': 'file-text',
  'help-circle': 'help-circle',
  'home': 'home',
  'information-circle-outline': 'info',
  'message-square': 'message-square',
  'ribbon-outline': 'award',
  'trending-up': 'trending-up',
  'person-circle': 'user',
  'menu': 'menu',
  'funnel': 'filter',
  'funnel-outline': 'filter',
  'swap-vertical': 'repeat',
  'checkmark-circle-outline': 'check-circle',
  'ellipse': 'more-horizontal',
  'ellipse-outline': 'more-horizontal',
  'copy': 'copy',
  'corner-up-right': 'corner-up-right',
  'chevron-right': 'chevron-right',
  'edit-2': 'edit-2',
  'more-vertical': 'more-vertical',
  'mic': 'mic',
};

// Icons that only exist in Ionicons (no Feather equivalent)
const IONICONS_ONLY = new Set([
  'help-buoy',
  'logo-whatsapp',
]);

export default function Icon({ name, size = 20, color, style, ...props }) {
  if (IONICONS_ONLY.has(name)) {
    return <Ionicons name={name} size={size} color={color} style={style} {...props} />;
  }
  const featherName = FEATHER_MAP[name];
  if (featherName) {
    return <Feather name={featherName} size={size} color={color} style={style} {...props} />;
  }
  return <Ionicons name={name} size={size} color={color} style={style} {...props} />;
}
